import Head from "next/head";
import Image from "next/image";
import Features from "../components/Features";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Form from "../components/Form";
import HeroConsumer from "../components/HeroConsumer";
import OurSolution from "../components/OurSolution";
import { Button } from "@mui/material";
import Navbar from "../components/Navbar";
import Layout from "../components/Layout";
import BarcodeSec from "../components/BarcodeSec";
import Partners from "../components/Partners";
import MerchantSec from "../components/MerchantSec";

export default function Home() {
  const ourSolution = (subtitle, image) => (
    <div className="flex flex-1 flex-col justify-center items-center  bg-[#F7F9FB] p-[3rem] text-center gap-[1rem]">
      <img src={image} />
      <h3>{subtitle}</h3>
    </div>
  );

  return (
    <div className="overflow-x-hidden">
      <Head>
        <title>Bienvenue </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/sticky-logo.svg" />
      </Head>
      <Header />
      <HeroConsumer />
      <div className="min-h-[100vh] container ">
        <div className=" flex items-center justify-center flex-col py-[4rem] lg:py-[6rem] text-center">
          <h2>Our solutions</h2>
          <p>
            It is a long established fact that a reader will be distracted by
            the readable content.
          </p>
        </div>
        <div className="flex flex-col md:flex-row gap-[3rem] p-[3rem] lg:p-[3rem]">
          {ourSolution("Digital Advertising", "images/digital-marketing.svg")}
          {ourSolution(
            "Enjoy more Brand visibilty",
            "images/brand-marketing.svg"
          )}
          {ourSolution("Data Reporting", "images/reporting.svg")}
        </div>
      </div>
      <Features
        image="images/m21.svg"
        heading="Merchant Dashboard"
        // background="#d3fbe9"
        //  style={{ background: background }}
        body={
          <div className="">
            <p className="mt-[.3rem] max-w-[30rem] ">
              It is a long established fact that a reader will be distracted by
              the readable content It is a long established fact that a reader
              will be distracted by the readable conent It is a long established
              fact that a reader will be distracted by the readable content.
            </p>
          </div>
        }
      />
      <BarcodeSec
        image="images/barcode.svg"
        heading="Barcode"
        sectionBackground="images/section-background.svg"
        body={
          <p className="max-w-[30rem]  ">
            It is a long established fact that a reader will be distracted by
            the readable content It is a long established fact that a reader
            will be distracted by the readable conent It is a long established
            fact that a reader will be distracted by the readable content.
          </p>
        }
      />
      <MerchantSec
        image="images/growing.svg"
        heading="Start growing with
          the BIENVENUE today"
        body={
          <div>
            <p className="">
              It is a long established fact that a reader will be distracted by
              the reader will be distracted by the readable content.
            </p>
            <Button className="bg-[#fdb912] hover:bg-[#fdb912] text-white p-[1rem] rounded-[12px] h-[55px] w-[170px] my-[2rem]">
              Join us now
            </Button>
          </div>
        }
      />
      <Partners />
      <Footer />
    </div>
  );
}
